### ISSUE TITLE
templatesをzipで持たないようにする

### ISSUE THREAD

**Issue by kamakiri01** [akashic-games/akashic-cli-init#4]
`templates/typescript.zip` に修正を入れる場合、zip圧縮されたファイルを変更してもgithub上で差分を確認できません。
解凍後のディレクトリ構造をtemplates/ 以下に持ち、テンプレートへの変更は akashic-cli-init への修正として出せるようにしたほうが良いと思います。

**Comment by xnv** [comment]
「解凍後のディレクトリ構造」には、 "package.json" という名前のファイルが含まれていて、このファイル名は `npm publish` 時に問題を起こしたと記憶しています。おそらくただテンプレートを展開するだけではなく、以下のような対応が必要だろうと思います:

- テンプレートは展開してリポジトリに抱えることにする (`template-sources/` (名前は適当) に置く)
- package.json の scripts フィールドに prepublish を追加し、 `template-sources/` 以下を圧縮して `templates/` に出力する
- package.json の files フィールドには `templates` を加える (これは現実装のまま)
- 実装はファクトリテンプレートを `templates/` から取得するようにする (これも現実装のまま)
