### ISSUE TITLE
`typescript` テンプレートだと、 `akashic install` が二度手間なのを直したい

### ISSUE THREAD

**Issue by ndxbn** [akashic-games/akashic-cli-init#5]
## 概要
`akashic init -t typescript` テンプレートで、npm パッケージを追加するときの処理を一つのコマンドにしておきたい。

## 
現状の `akashic init -t typescript` で作成されるテンプレートの場合、 README.md にも書いてある通り、以下のようにしてライブラリ（≒npm パッケージ）を追加します。

```bash
# on root
npm install --save <package_name>
cd game
akashic install <package_name>
```

この処理は原子性のある操作なので、手動でやらず、一つのコマンドとして提供した方がいいと思います。  
例えば、`@akashic-extension/akashic-timeline`  を追加したい機会などは、比較的多いと思います。

**Comment by xnv** [comment]
なるほど、これは typescript テンプレート固有の話題なので、 `akashic` コマンドではなくテンプレート内で解決したいですね……。 ("javascript" テンプレートにこのような install の二重性はありません) 
直感的には typescript テンプレートの直下で

```
npm run install-game-lib @akashic-extension/akashic-timeline
```

みたいなことができるようになると良さそうに思えますが、いかがでしょう。

**Comment by xnv** [comment]
#4 の後に対応します。

**Comment by xnv** [comment]
……結局上記対応を行ったか記憶が曖昧なのですが、その後 template を更新して、既に二段構成ではなくなっているのでこの問題は解消しました。クローズします。
